module.exports = {
    INVALID_REQUEST : "Invalid request",
    BAD_REQUEST:'Bad Request',
    OUT_OF_BOUND:'out of bound or invalid',
    INVALID_EMAIL: "Email invalid",
    USER_VERIFIED: "User verified successfully",
    USER_NOT_VERIFIED: "User email not verified",
    USER_NOT_EXIST: "user not exist",
    USER_EXIST: "user already exist",
    USER_CREATED: "user created successfully",
    USER_EDITED: "user edited successfully",
    INVALID_PASSWORD: "Inavlid Password",
    USER_LOGGED_OUT:'user logged out successfully',
    QUESTION_OPTION_EMPTY:'Option should not be empty',
    QUESTION_OPTIONS_REQUIRED:'Atlest 2 options are required',
    PASSWORD_DONT_MATCH: "Password dosen't match",
    PASSWORD_CHANGED: "password changed successfully",
    INTERNAL_SERVER_ERROR:'Internal Server Error',
    INVALID_CREDENTIALS:'invalid credentials',
    USER_LOGEDIN:'User Logged in sucessfully',
    TOKEN_REQUIRED:"An authentication token is required",
    INVALID_TOKEN:'Invalid token',
    QUIZ_CREATED:'Quiz created successfully',
    QUIZ_NOT_FOUND:'No quiz found',
    QUIZ_FETCHED:'Quiz fetched succesfully',
    QUIZ_DELETED:'Quiz deleted succesfully',
    QUIZ_RESULTS_REQUIRED:'Quiz results are required',
    QUESTION_NOT_FOUND:'Question not found',
    QUIZ_COMPLETE:'Quiz attempted succesfully',
    QUIZ_UPDATED:'Quiz updated succesfully',
    QUIZ_NAME_REQUIRED:'Quiz name is required',
    QUIZ_TIMER_REQUIRED:'Timer is required',
    QUESTIONS_REQUIRED:'Question are required',
    QUIZ_ANALYSIS_FETCHED:'Quiz analysis fetched sucessfully',
    QUESTION_OPTIONS_INVALID:"Each question must have between 2 and 4 options",
    MAX_QUESTIONS_EXCEEDED:'A maximum of 5 questions is allowed',
    POLL_CREATED:'Poll created successfully',
    POLL_NOT_FOUND:'No Poll found',
    POLL_FETCHED:'Polls fetched succesfully',
    POLL_DELETED:'Poll deleted succesfully',
    POLL_RESULTS_REQUIRED:'Poll results are required',
    POLL_ANALYSIS_FETCHED:'Poll analysis fetched sucessfully',
    QUESTION_NOT_FOUND:'Question not found',
    POLL_COMPLETE:'Poll attempted succesfully',
    POLL_UPDATED:'Poll updated succesfully',
    POLL_NAME_REQUIRED:'Poll name is required',
    DATA_FETCHED:'Data fetched successfully',
    TEXT_OPTION_EMPTY:"text should not be empty",
    IMAGE_OPTION_EMPTY:"Image URL should not be empty",
    TEXT_IMAGE_OPTION_EMPTY:"text and Image URL should not be empty",
    
}